// megafunction wizard: %ALTMULT_COMPLEX%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altmult_complex 

// ============================================================
// File Name: cmplx_mult_clk.v
// Megafunction Name(s):
// 			altmult_complex
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 13.0.1 Build 232 06/12/2013 SP 1 SJ Web Edition
// ************************************************************


//Copyright (C) 1991-2013 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//altmult_complex CBX_AUTO_BLACKBOX="ALL" DEVICE_FAMILY="Cyclone II" IMPLEMENTATION_STYLE="AUTO" PIPELINE=1 REPRESENTATION_A="SIGNED" REPRESENTATION_B="SIGNED" WIDTH_A=32 WIDTH_B=32 WIDTH_RESULT=64 clock dataa_imag dataa_real datab_imag datab_real result_imag result_real
//VERSION_BEGIN 13.0 cbx_alt_ded_mult_y 2013:06:12:18:03:43:SJ cbx_altera_mult_add 2013:06:12:18:03:43:SJ cbx_altera_mult_add_rtl 2013:06:12:18:03:43:SJ cbx_altmult_add 2013:06:12:18:03:43:SJ cbx_altmult_complex 2013:06:12:18:03:43:SJ cbx_arriav 2013:06:12:18:03:43:SJ cbx_cycloneii 2013:06:12:18:03:43:SJ cbx_lpm_add_sub 2013:06:12:18:03:43:SJ cbx_lpm_compare 2013:06:12:18:03:43:SJ cbx_lpm_mult 2013:06:12:18:03:43:SJ cbx_mgl 2013:06:12:18:05:10:SJ cbx_padd 2013:06:12:18:03:43:SJ cbx_parallel_add 2013:06:12:18:03:43:SJ cbx_stratix 2013:06:12:18:03:43:SJ cbx_stratixii 2013:06:12:18:03:43:SJ cbx_stratixv 2013:06:12:18:03:43:SJ cbx_util_mgl 2013:06:12:18:03:43:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = altmult_add 2 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  cmplx_mult_clk_altmult_complex_i4p
	( 
	clock,
	dataa_imag,
	dataa_real,
	datab_imag,
	datab_real,
	result_imag,
	result_real) ;
	input   clock;
	input   [31:0]  dataa_imag;
	input   [31:0]  dataa_real;
	input   [31:0]  datab_imag;
	input   [31:0]  datab_real;
	output   [63:0]  result_imag;
	output   [63:0]  result_real;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [63:0]   wire_mult_add1_result;
	wire  [63:0]   wire_mult_add2_result;
	wire aclr;
	wire ena;
	wire  [63:0]  mult_add1_inputa;
	wire  [63:0]  mult_add1_inputb;
	wire  [63:0]  mult_add2_inputb;

	altmult_add   mult_add1
	( 
	.aclr0(aclr),
	.chainout_sat_overflow(),
	.clock0(clock),
	.dataa(mult_add1_inputa),
	.datab(mult_add1_inputb),
	.ena0(ena),
	.mult0_is_saturated(),
	.mult1_is_saturated(),
	.mult2_is_saturated(),
	.mult3_is_saturated(),
	.overflow(),
	.result(wire_mult_add1_result),
	.scanouta(),
	.scanoutb()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.accum_sload(1'b0),
	.aclr1(1'b0),
	.aclr2(1'b0),
	.aclr3(1'b0),
	.addnsub1(1'b1),
	.addnsub1_round(1'b0),
	.addnsub3(1'b1),
	.addnsub3_round(1'b0),
	.chainin({1{1'b0}}),
	.chainout_round(1'b0),
	.chainout_saturate(1'b0),
	.clock1(1'b1),
	.clock2(1'b1),
	.clock3(1'b1),
	.coefsel0({3{1'b0}}),
	.coefsel1({3{1'b0}}),
	.coefsel2({3{1'b0}}),
	.coefsel3({3{1'b0}}),
	.datac({44{1'b0}}),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.mult01_round(1'b0),
	.mult01_saturation(1'b0),
	.mult23_round(1'b0),
	.mult23_saturation(1'b0),
	.output_round(1'b0),
	.output_saturate(1'b0),
	.rotate(1'b0),
	.scanina({32{1'b0}}),
	.scaninb({32{1'b0}}),
	.shift_right(1'b0),
	.signa(1'b0),
	.signb(1'b0),
	.sourcea({2{1'b0}}),
	.sourceb({2{1'b0}}),
	.zero_chainout(1'b0),
	.zero_loopback(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	defparam
		mult_add1.input_register_a0 = "UNREGISTERED",
		mult_add1.input_register_a1 = "UNREGISTERED",
		mult_add1.input_register_b0 = "UNREGISTERED",
		mult_add1.input_register_b1 = "UNREGISTERED",
		mult_add1.multiplier1_direction = "SUB",
		mult_add1.multiplier_register0 = "UNREGISTERED",
		mult_add1.multiplier_register1 = "UNREGISTERED",
		mult_add1.number_of_multipliers = 2,
		mult_add1.output_aclr = "ACLR0",
		mult_add1.output_register = "CLOCK0",
		mult_add1.port_addnsub1 = "PORT_UNUSED",
		mult_add1.port_signa = "PORT_UNUSED",
		mult_add1.port_signb = "PORT_UNUSED",
		mult_add1.representation_a = "SIGNED",
		mult_add1.representation_b = "SIGNED",
		mult_add1.width_a = 32,
		mult_add1.width_b = 32,
		mult_add1.width_result = 64,
		mult_add1.lpm_type = "altmult_add";
	altmult_add   mult_add2
	( 
	.aclr0(aclr),
	.chainout_sat_overflow(),
	.clock0(clock),
	.dataa(mult_add1_inputa),
	.datab(mult_add2_inputb),
	.ena0(ena),
	.mult0_is_saturated(),
	.mult1_is_saturated(),
	.mult2_is_saturated(),
	.mult3_is_saturated(),
	.overflow(),
	.result(wire_mult_add2_result),
	.scanouta(),
	.scanoutb()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.accum_sload(1'b0),
	.aclr1(1'b0),
	.aclr2(1'b0),
	.aclr3(1'b0),
	.addnsub1(1'b1),
	.addnsub1_round(1'b0),
	.addnsub3(1'b1),
	.addnsub3_round(1'b0),
	.chainin({1{1'b0}}),
	.chainout_round(1'b0),
	.chainout_saturate(1'b0),
	.clock1(1'b1),
	.clock2(1'b1),
	.clock3(1'b1),
	.coefsel0({3{1'b0}}),
	.coefsel1({3{1'b0}}),
	.coefsel2({3{1'b0}}),
	.coefsel3({3{1'b0}}),
	.datac({44{1'b0}}),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.mult01_round(1'b0),
	.mult01_saturation(1'b0),
	.mult23_round(1'b0),
	.mult23_saturation(1'b0),
	.output_round(1'b0),
	.output_saturate(1'b0),
	.rotate(1'b0),
	.scanina({32{1'b0}}),
	.scaninb({32{1'b0}}),
	.shift_right(1'b0),
	.signa(1'b0),
	.signb(1'b0),
	.sourcea({2{1'b0}}),
	.sourceb({2{1'b0}}),
	.zero_chainout(1'b0),
	.zero_loopback(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	);
	defparam
		mult_add2.input_register_a0 = "UNREGISTERED",
		mult_add2.input_register_a1 = "UNREGISTERED",
		mult_add2.input_register_b0 = "UNREGISTERED",
		mult_add2.input_register_b1 = "UNREGISTERED",
		mult_add2.multiplier1_direction = "ADD",
		mult_add2.multiplier_register0 = "UNREGISTERED",
		mult_add2.multiplier_register1 = "UNREGISTERED",
		mult_add2.number_of_multipliers = 2,
		mult_add2.output_aclr = "ACLR0",
		mult_add2.output_register = "CLOCK0",
		mult_add2.port_addnsub1 = "PORT_UNUSED",
		mult_add2.port_signa = "PORT_UNUSED",
		mult_add2.port_signb = "PORT_UNUSED",
		mult_add2.representation_a = "SIGNED",
		mult_add2.representation_b = "SIGNED",
		mult_add2.width_a = 32,
		mult_add2.width_b = 32,
		mult_add2.width_result = 64,
		mult_add2.lpm_type = "altmult_add";
	assign
		aclr = 1'b0,
		ena = 1'b1,
		mult_add1_inputa = {dataa_imag[31:0], dataa_real[31:0]},
		mult_add1_inputb = {datab_imag[31:0], datab_real[31:0]},
		mult_add2_inputb = {datab_real[31:0], datab_imag[31:0]},
		result_imag = wire_mult_add2_result,
		result_real = wire_mult_add1_result;
endmodule //cmplx_mult_clk_altmult_complex_i4p
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module cmplx_mult_clk (
	clock,
	dataa_imag,
	dataa_real,
	datab_imag,
	datab_real,
	result_imag,
	result_real);

	input	  clock;
	input	[31:0]  dataa_imag;
	input	[31:0]  dataa_real;
	input	[31:0]  datab_imag;
	input	[31:0]  datab_real;
	output	[63:0]  result_imag;
	output	[63:0]  result_real;

	wire [63:0] sub_wire0;
	wire [63:0] sub_wire1;
	wire [63:0] result_imag = sub_wire0[63:0];
	wire [63:0] result_real = sub_wire1[63:0];

	cmplx_mult_clk_altmult_complex_i4p	cmplx_mult_clk_altmult_complex_i4p_component (
				.clock (clock),
				.dataa_imag (dataa_imag),
				.dataa_real (dataa_real),
				.datab_imag (datab_imag),
				.datab_real (datab_real),
				.result_imag (sub_wire0),
				.result_real (sub_wire1));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone II"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: IMPLEMENTATION_STYLE STRING "AUTO"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone II"
// Retrieval info: CONSTANT: PIPELINE NUMERIC "1"
// Retrieval info: CONSTANT: REPRESENTATION_A STRING "SIGNED"
// Retrieval info: CONSTANT: REPRESENTATION_B STRING "SIGNED"
// Retrieval info: CONSTANT: WIDTH_A NUMERIC "32"
// Retrieval info: CONSTANT: WIDTH_B NUMERIC "32"
// Retrieval info: CONSTANT: WIDTH_RESULT NUMERIC "64"
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT NODEFVAL "clock"
// Retrieval info: USED_PORT: dataa_imag 0 0 32 0 INPUT NODEFVAL "dataa_imag[31..0]"
// Retrieval info: USED_PORT: dataa_real 0 0 32 0 INPUT NODEFVAL "dataa_real[31..0]"
// Retrieval info: USED_PORT: datab_imag 0 0 32 0 INPUT NODEFVAL "datab_imag[31..0]"
// Retrieval info: USED_PORT: datab_real 0 0 32 0 INPUT NODEFVAL "datab_real[31..0]"
// Retrieval info: USED_PORT: result_imag 0 0 64 0 OUTPUT NODEFVAL "result_imag[63..0]"
// Retrieval info: USED_PORT: result_real 0 0 64 0 OUTPUT NODEFVAL "result_real[63..0]"
// Retrieval info: CONNECT: @clock 0 0 0 0 clock 0 0 0 0
// Retrieval info: CONNECT: @dataa_imag 0 0 32 0 dataa_imag 0 0 32 0
// Retrieval info: CONNECT: @dataa_real 0 0 32 0 dataa_real 0 0 32 0
// Retrieval info: CONNECT: @datab_imag 0 0 32 0 datab_imag 0 0 32 0
// Retrieval info: CONNECT: @datab_real 0 0 32 0 datab_real 0 0 32 0
// Retrieval info: CONNECT: result_imag 0 0 64 0 @result_imag 0 0 64 0
// Retrieval info: CONNECT: result_real 0 0 64 0 @result_real 0 0 64 0
// Retrieval info: GEN_FILE: TYPE_NORMAL cmplx_mult_clk.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL cmplx_mult_clk.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL cmplx_mult_clk.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL cmplx_mult_clk.bsf TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL cmplx_mult_clk_inst.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL cmplx_mult_clk_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL cmplx_mult_clk_syn.v TRUE
// Retrieval info: LIB_FILE: altera_mf
